global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'envoy'
    static_configs:
      - targets: ['envoy:9901']

  - job_name: 'web-service'
    static_configs:
      - targets: ['web:8080']

  - job_name: 'api-service'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:9249']

